### ISSUE TITLE
Config Formatting Issue?

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/KeckDRPFramework#28]
I'm trying to follow the instructions to create a new DRP from the framework.  I've used the template included in the framework, but when I try to run my dummy pipeline I get this:

```
(base) [joshw] ~/git/MOSFIRE_DataMonitor > python scripts/template_script.py -c config.cfg -frames=file1.fits
Traceback (most recent call last):
  File "scripts/template_script.py", line 53, in <module>
    config = ConfigClass(args.config_file)
  File "/Users/jwalawender/anaconda/lib/python3.6/site-packages/keckdrpframework-0.0.dev102-py3.6.egg/keckdrpframework/config/framework_config.py", line 50, in __init__
    self.read(cgfile)
  File "/Users/jwalawender/anaconda/lib/python3.6/site-packages/keckdrpframework-0.0.dev102-py3.6.egg/keckdrpframework/config/framework_config.py", line 109, in read
    super().read(path)
  File "/Users/jwalawender/anaconda/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/jwalawender/anaconda/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'config.cfg', line: 11
"name = 'MOSFIRE-Data-Monitor'\n"
```

It looks like there might be an issue with the default config file, but I'm not sure how to interpret this error.

**Comment by shkw0k** [comment]
Added default section. Merged to develop.

**Comment by shkw0k** [comment]
Closed

**Comment by MosfireDRP** [comment]
Josh I am afraid that the template has not kept up with the development. 

It is in my plan to update the template soon 

It might be easier to start from a real pipeline right now, like the KCWI pipeline. 
Let me know if you are interested
