### ISSUE TITLE
Package Import Breaks for Python >= 3.12

### ISSUE THREAD

**Issue by bjfultn** [Keck-DataReductionPipelines/KeckDRPFramework#63]
- distutils is no longer part of python >= 3.12.
- Line 13 in __init__.py breaks the import for the latest python versions:
```
from distutils.version import LooseVersion
```

**Comment by BMazzilliCiraulo** [comment]
I'm encountering the same problem. I've raised it on the KCWI_DRP github page.

**Comment by astrobc1** [comment]
**Using**:
Python 3.11.9
Latest develop branch of keckdrpframework

```
>>> from pkg_resources import parse_version
>>> import sys
>>> sys.version
'3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]'
>>> parse_version(sys.version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/hispecdrp_env/lib/python3.11/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: {version!r}")
packaging.version.InvalidVersion: Invalid version: '3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]'
>>> parse_version(sys.version[:7])
<Version('3.11.9')>
>>> 
```

So it looks like `parse_version` doesn't like the extra info after the "9". I can reproduce this on 3.12 as well.

Another way to parse the version is with
```ver = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"```
